# .streamlit/secrets.toml

[connections.snowflake]
account = "CLUHTKZ.RH10718"
user = "pennidhii"
password = "Pennidhi*9"
role = "sysadmin"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
